#############################################################################
# Makefile for building: chessdatabase
# Generated by qmake (1.07a) (Qt 3.3.4) on: Tue May 17 15:41:53 2005
# Project:  chessdatabase.pro
# Template: subdirs
# Command: $(QMAKE) -o Makefile chessdatabase.pro
#############################################################################

MAKEFILE =	Makefile
QMAKE    =	qmake
DEL_FILE =    rm -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p
INSTALL_FILE= 
INSTALL_DIR = 
SUBTARGETS =	 \
		sub-src-database \
		sub-src-gui \
		sub-src

first: all

all: Makefile $(SUBTARGETS)

src/database/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) "src/database" || $(MKDIR) "src/database"
	cd src/database && $(QMAKE) database.pro -o $(MAKEFILE)
sub-src-database: src/database/$(MAKEFILE) FORCE
	cd src/database && $(MAKE) -f $(MAKEFILE)

src/gui/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) "src/gui" || $(MKDIR) "src/gui"
	cd src/gui && $(QMAKE) gui.pro -o $(MAKEFILE)
sub-src-gui: src/gui/$(MAKEFILE) FORCE
	cd src/gui && $(MAKE) -f $(MAKEFILE)

src/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) "src" || $(MKDIR) "src"
	cd src && $(QMAKE) src.pro -o $(MAKEFILE)
sub-src: src/$(MAKEFILE) FORCE
	cd src && $(MAKE) -f $(MAKEFILE)

Makefile: chessdatabase.pro  /usr/qt/3/mkspecs/linux-g++/qmake.conf 
	$(QMAKE) -o Makefile chessdatabase.pro
qmake: qmake_all
	@$(QMAKE) -o Makefile chessdatabase.pro

all: $(SUBTARGETS)
qmake_all: src/database/$(MAKEFILE) src/gui/$(MAKEFILE) src/$(MAKEFILE)
	 ( [ -d src/database ] && cd src/database ; grep "^qmake_all:" $(MAKEFILE) && $(MAKE) -f $(MAKEFILE) qmake_all; ) || true
	 ( [ -d src/gui ] && cd src/gui ; grep "^qmake_all:" $(MAKEFILE) && $(MAKE) -f $(MAKEFILE) qmake_all; ) || true
	 ( [ -d src ] && cd src ; grep "^qmake_all:" $(MAKEFILE) && $(MAKE) -f $(MAKEFILE) qmake_all; ) || true
clean uicables mocables uiclean mocclean lexclean yaccclean : qmake_all FORCE
	 ( [ -d src/database ] && cd src/database ; $(MAKE) -f $(MAKEFILE) $@; ) || true
	 ( [ -d src/gui ] && cd src/gui ; $(MAKE) -f $(MAKEFILE) $@; ) || true
	 ( [ -d src ] && cd src ; $(MAKE) -f $(MAKEFILE) $@; ) || true
uninstall_subdirs: qmake_all FORCE
	 ( [ -d src/database ] && cd src/database ; $(MAKE) -f $(MAKEFILE) uninstall; ) || true
	 ( [ -d src/gui ] && cd src/gui ; $(MAKE) -f $(MAKEFILE) uninstall; ) || true
	 ( [ -d src ] && cd src ; $(MAKE) -f $(MAKEFILE) uninstall; ) || true
install_subdirs: qmake_all FORCE
	 ( [ -d src/database ] && cd src/database ; $(MAKE) -f $(MAKEFILE) install; ) || true
	 ( [ -d src/gui ] && cd src/gui ; $(MAKE) -f $(MAKEFILE) install; ) || true
	 ( [ -d src ] && cd src ; $(MAKE) -f $(MAKEFILE) install; ) || true
distclean: qmake_all FORCE
	 ( [ -d src/database ] && cd src/database ; $(MAKE) -f $(MAKEFILE) $@; $(DEL_FILE) $(MAKEFILE); ) || true
	 ( [ -d src/gui ] && cd src/gui ; $(MAKE) -f $(MAKEFILE) $@; $(DEL_FILE) $(MAKEFILE); ) || true
	 ( [ -d src ] && cd src ; $(MAKE) -f $(MAKEFILE) $@; $(DEL_FILE) $(MAKEFILE); ) || true

install:  install_subdirs

uninstall:  uninstall_subdirs

FORCE:

