#!/bin/sh
/opt/subversion/bin/svn log > /tmp/svn.log
grep "New Feature" /tmp/svn.log | sed -e 's/^/- /'
grep "New feature" /tmp/svn.log | sed -e 's/^/- /'
grep "Bugfix"      /tmp/svn.log | sed -e 's/^/- /'
grep "Changed"     /tmp/svn.log | sed -e 's/^/- /'
